// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPerson struct {
	Name        *string `json:"Name,omitempty"`
	Surname     *string `json:"Surname,omitempty"`
	Patronymic  *string `json:"Patronymic,omitempty"`
	Age         *int    `json:"Age,omitempty"`
	Gender      *string `json:"Gender,omitempty"`
	Nationality *string `json:"Nationality,omitempty"`
}

type Person struct {
	ID          string `json:"Id"`
	Name        string `json:"Name"`
	Surname     string `json:"Surname"`
	Patronymic  string `json:"Patronymic"`
	Age         int    `json:"Age"`
	Gender      string `json:"Gender"`
	Nationality string `json:"Nationality"`
}
